### PR TITLE
Fix #40: splice on select

### LINKED ISSUE #40: q"xs.map(_ + 3)" doesn't work
q"xs.map(_ + 3)" doesn't work

### PR DESCRIPTION
**Pull request by liufengyun**
Fix #40: splice on select

### CODE REVIEW

File: src/main/scala/gestalt/Quote.scala [hunk 1]
```diff
@@ -183,7 +183,7 @@ abstract class Quote(val t: Toolbox, val toolboxName: String) {
       // Infix is sugar-less
       // the List is constructed as Nil.::(c).::(b).::(a)
       // Not a :: b :: c :: Nil
```
Comment (valdisxp1) [inline src/main/scala/gestalt/Quote.scala]: Nice, `Infix` works properly now!
The comment now is wrong, and should be removed.

**Comment by liufengyun** [comment]
I added some helper constructors in this PR, also added `Update`, `Pat.Var`, `Pat.Unapply`, `Pat.Ascribe`, `Pat.Tuple`, `Pat.Infix`. `Ident` and `Lit` are assumed to be patterns. The types stay the same as type trees, this simplifies things while remains to be a fair assumption.

The main reason for having separate constructors for patterns is portability -- as those things are semantically very different from expressions.

But I don't think it's good to provide extractors for them, it's insane to change patterns in user-code, it's too brittle.

**Comment by liufengyun** [comment]
I'm merging this now, I hope quasiquotes are more robust now. There are certainly more bugs, but we can fix them gradually.
